// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB50Dj23-uRMO9IAoB7P7eFA9V_y8uvRds',
    appId: '1:354589477987:web:78ba0c1368cdd7ed273c56',
    messagingSenderId: '354589477987',
    projectId: 'weddyweddy',
    authDomain: 'weddyweddy.firebaseapp.com',
    storageBucket: 'weddyweddy.appspot.com',
    measurementId: 'G-4X32WBB1Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTLIdWdI997Pq0Z9xvEKfVz-jgZpRhPxE',
    appId: '1:354589477987:android:7ac6dba56d90065c273c56',
    messagingSenderId: '354589477987',
    projectId: 'weddyweddy',
    storageBucket: 'weddyweddy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9iAWf0jibk3hAYG3oHsEO9WihoG194mI',
    appId: '1:354589477987:ios:5643ad88a006b5e9273c56',
    messagingSenderId: '354589477987',
    projectId: 'weddyweddy',
    storageBucket: 'weddyweddy.appspot.com',
    androidClientId: '354589477987-ji20c4epnl16m034te8a66hhl145odu7.apps.googleusercontent.com',
    iosClientId: '354589477987-4jfku7d1uglqp2se8efn9ret2ml9i2il.apps.googleusercontent.com',
    iosBundleId: 'com.weddy.weddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9iAWf0jibk3hAYG3oHsEO9WihoG194mI',
    appId: '1:354589477987:ios:5643ad88a006b5e9273c56',
    messagingSenderId: '354589477987',
    projectId: 'weddyweddy',
    storageBucket: 'weddyweddy.appspot.com',
    androidClientId: '354589477987-ji20c4epnl16m034te8a66hhl145odu7.apps.googleusercontent.com',
    iosClientId: '354589477987-4jfku7d1uglqp2se8efn9ret2ml9i2il.apps.googleusercontent.com',
    iosBundleId: 'com.weddy.weddy',
  );
}
