// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJDNlGo84Y1rzZBcfHwjRmIhCH-LrhjVU',
    appId: '1:129761713814:web:61b544960e4cd03ed1ecb7',
    messagingSenderId: '129761713814',
    projectId: 'weddy-430d7',
    authDomain: 'weddy-430d7.firebaseapp.com',
    storageBucket: 'weddy-430d7.appspot.com',
    measurementId: 'G-SWV0ZMKMTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZAdQFxlqzcRGLr-y6CSsszZUrinrnbMo',
    appId: '1:129761713814:android:12995ab70bac956cd1ecb7',
    messagingSenderId: '129761713814',
    projectId: 'weddy-430d7',
    storageBucket: 'weddy-430d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTdAWPp-XRqwJGZKs5Bwy0_5K8L3Fntys',
    appId: '1:129761713814:ios:ee387454d16e804ed1ecb7',
    messagingSenderId: '129761713814',
    projectId: 'weddy-430d7',
    storageBucket: 'weddy-430d7.appspot.com',
    iosClientId: '129761713814-cfau1taivp47jjjeqciq1stkr75nb179.apps.googleusercontent.com',
    iosBundleId: 'com.weddy.weddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTdAWPp-XRqwJGZKs5Bwy0_5K8L3Fntys',
    appId: '1:129761713814:ios:ee387454d16e804ed1ecb7',
    messagingSenderId: '129761713814',
    projectId: 'weddy-430d7',
    storageBucket: 'weddy-430d7.appspot.com',
    iosClientId: '129761713814-cfau1taivp47jjjeqciq1stkr75nb179.apps.googleusercontent.com',
    iosBundleId: 'com.weddy.weddy',
  );
}
